formatting:
  NoWildcardImports:
    active: false

style:
  WildcardImport:
    active: false
  MagicNumber:
    active: true
    excludes:
      - '/theme/'
      - '**/ui/theme/Color.kt'

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]

complexity:
  LongParameterList:
    active: true
    threshold: 6
    ignoreAnnotated: [ 'Composable' ]
    excludes:
      - '**/ui/home/HomeViewModel.kt'
      - '**/ui/detail/ProductDetailViewModel.kt'
      - '**/ui/theme/Color.kt'
      - '**/data/mapper/Mappers.kt'
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated: [ 'Composable' ]
  TooManyFunctions:
    active: true
    excludes:
      - '**/repository/ProductRepositoryImpl.kt'
      - '**/repository/ProductRepository.kt'

exceptions:
  TooGenericExceptionCaught:
    active: false




